### ISSUE TITLE
Markdown text color is displayed incorrectly

### ISSUE THREAD

**Issue by Jannik-Schroeder** [Jannik-Schroeder/portfolio#2]
Currently, we are facing an issue with the display of Markdown text colors.

**Comment by Jannik-Schroeder** [comment]
![Screenshot 2023-05-09 100805](https://user-images.githubusercontent.com/90240332/237035127-3dfe1112-1346-434c-94ef-b6a0cd2cd5ee.jpg)

**Comment by DanielWTE** [comment]
Fixed with following commit #4
